# https://github.com/vn7n24fzkq/github-profile-summary-cards?tab=readme-ov-file#github-actions-usage
name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron:  '0 15 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.README_STATS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true