# https://github.com/vn7n24fzkq/github-profile-summary-cards?tab=readme-ov-file#github-actions-usage
name: GitHub-Profile-Summary-Cards

on:
  workflow_run:
    workflows: [Generate Snake Animation]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.README_STATS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "output"
          UTC_OFFSET: 9
          EXCLUDE: ""
          AUTO_PUSH: true